//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Links {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Links() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Links", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /en/About/sale-rent-property-marketing-Lebanon.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /ar/نبذة-عنا.
        /// </summary>
        internal static string ArabicAbout {
            get {
                return ResourceManager.GetString("ArabicAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /ar/عقارات-للبيع-لبنان.
        /// </summary>
        internal static string ArabicBuy {
            get {
                return ResourceManager.GetString("ArabicBuy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /ar/أتصل-بنا.
        /// </summary>
        internal static string ArabicContact {
            get {
                return ResourceManager.GetString("ArabicContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /ar/الملاحظات.
        /// </summary>
        internal static string ArabicFeedback {
            get {
                return ResourceManager.GetString("ArabicFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /ar/الاستثمارات-العقارية-لبنان.
        /// </summary>
        internal static string ArabicInvestments {
            get {
                return ResourceManager.GetString("ArabicInvestments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /ar/رهن-قروض-سكنية-لبنان.
        /// </summary>
        internal static string ArabicMortages {
            get {
                return ResourceManager.GetString("ArabicMortages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /ar/لمحة-عنا.
        /// </summary>
        internal static string ArabicProfile {
            get {
                return ResourceManager.GetString("ArabicProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /ar/عقارات-للأيجار-لبنان.
        /// </summary>
        internal static string ArabicRent {
            get {
                return ResourceManager.GetString("ArabicRent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /ar/خدمات-عقارية-لبنان.
        /// </summary>
        internal static string ArabicServices {
            get {
                return ResourceManager.GetString("ArabicServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /en/real-estate-for-sale/Lebanon.
        /// </summary>
        internal static string Buy {
            get {
                return ResourceManager.GetString("Buy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /fr/qui-sommes-nous.
        /// </summary>
        internal static string FrenchAbout {
            get {
                return ResourceManager.GetString("FrenchAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /fr/acheter-appartement-immobilier/Liban.
        /// </summary>
        internal static string FrenchBuy {
            get {
                return ResourceManager.GetString("FrenchBuy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /fr/pret-immobilier-liban.
        /// </summary>
        internal static string FrenchMortages {
            get {
                return ResourceManager.GetString("FrenchMortages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /fr/louer-appartement-bureaux-Liban.
        /// </summary>
        internal static string FrenchRent {
            get {
                return ResourceManager.GetString("FrenchRent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /fr/services-conseil-en-immobilier-gestion-locative-syndic.
        /// </summary>
        internal static string FrenchServices {
            get {
                return ResourceManager.GetString("FrenchServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lebanon.
        /// </summary>
        internal static string Lebanon {
            get {
                return ResourceManager.GetString("Lebanon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /en/mortages.
        /// </summary>
        internal static string Mortages {
            get {
                return ResourceManager.GetString("Mortages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /en/real-estate-for-rent-apartments-offices-Lebanon.
        /// </summary>
        internal static string Rent {
            get {
                return ResourceManager.GetString("Rent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /en/services-realestate-consultant-property-management.
        /// </summary>
        internal static string Services {
            get {
                return ResourceManager.GetString("Services", resourceCulture);
            }
        }
    }
}
